### ISSUE TITLE
Switch from unittests to integration tests for sha1 APKs Fennec when Autograph 2.5.0 is rolled-out

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla-releng/signingscript#90]
In https://github.com/mozilla-releng/signingscript/commit/a940b94333a67ce6abce967deeda86e7d4ce38d0 the `autograph_fennec_sha` signing format is enriched by signingscript with a `pkdigest7`: `SHA` additional option in the request to Autograph. Until that's deployed on Autograph as well, it's harmless as it's being ignored.

**Comment by MihaiTabara** [comment]
https://hub.docker.com/r/mozilla/autograph/tags/ now contains `2.5.0` which has the fix for both DSA key support but also `SHA`. 

It's still not yet deployed to Autograph production. Most likely in the next 48h

**Comment by mitchhentges** [comment]
Fixed by #96
